# Generated by Django 6.0 on 2026-01-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_userdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategoryDb',
        ),
        migrations.DeleteModel(
            name='UserDb',
        ),
    ]
