# Generated by Django 6.0 on 2026-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0003_delete_servicecategorydb_delete_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('category_image', models.ImageField(upload_to='category_image')),
            ],
        ),
    ]
