# Generated by Django 6.0 on 2026-01-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDb',
        ),
    ]
