# Generated by Django 6.0 on 2026-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0006_delete_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_role', models.CharField(choices=[('SERVICE_PROVIDER', 'Service Provider'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
