# Generated by Django 6.0 on 2026-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_serviceproviderprofiledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofiledb',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofiledb',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
