# Generated by Django 6.0 on 2026-02-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_serviceproviderprofiledb_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofiledb',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
