# Generated by Django 6.0 on 2026-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_serviceproviderprofiledb_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofiledb',
            name='address',
        ),
    ]
