# Generated by Django 6.0 on 2026-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_remove_customerprofiledb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofiledb',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofiledb',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
