# Generated by Django 6.0 on 2026-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_paymentdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdb',
            name='travel_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
