# Generated by Django 6.0 on 2026-02-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_userdb_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='username',
        ),
        migrations.AlterField(
            model_name='userdb',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
