# Generated by Django 6.0 on 2026-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_remove_userdb_email_remove_userdb_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderprofiledb',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
